# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HTTPTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HTTPTest
pod 'Alamofire', '~> 4.7'
  target 'HTTPTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HTTPTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
